version: "3.7"
services:
        database:
                build: ./db
                environment:
    
                       
                        MYSQL_DATABASE: flask-db
                        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
                ports:
                        - target: 3306
                          published: 3306
                          protocol: tcp

                          
        flask-app:
                build: ./flask-app
                ports:
                        - target: 5000
                          published: 5000
                          protocol: tcp
                depends_on:
                        - database 
                environment:
                        DATABASE_URI: ${DATABASE_URI}
                
                
                
        nginx:
                image: nginx:latest
                ports:
                        - target: 80
                          published: 80
                          protocol: tcp
                volumes:
                        - type: bind
                          source: ./nginx/nginx.conf
                          target: /etc/nginx/nginx.conf
